make entry script run on different python, like with RHEL8 that has only python3

diff --git a/bin/spack-deploy b/bin/spack-deploy
--- a/bin/spack-deploy
+++ b/bin/spack-deploy
@@ -1,4 +1,21 @@
-#!/usr/bin/env python
+#!/bin/sh
+# -*- python -*-
+#
+# This file is bilingual. The following shell code finds our preferred python.
+# Following line is a shell no-op, and starts a multi-line Python comment.
+# See https://stackoverflow.com/a/47886254
+""":"
+# prefer python3, then python, then python2
+for cmd in python3 python python2; do
+   command -v > /dev/null $cmd && exec $cmd $0 "$@"
+done
+
+echo "==> Error: spack could not find a python interpreter!" >&2
+exit 1
+":"""
+# Line above is a shell no-op, and ends a python multi-line comment.
+# The code above runs this file with our preferred python interpreter.
+
 
 import os
 import sys
